interactive_ui/accounts/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
]

interactive_ui/interactive_player/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = "interactive_player"

urlpatterns = [
    path('', views.index, name="index"),
    path('rtc', views.rtcdemo, name="rtcdemo"),
    path('rtc1', views.rtcmetatrack, name="rtcmetatrack"),
    url(r'^feedback', views.UserFeedbackView, name='feedback'),
    url(r'^downcount', views.downcount, name='downcount'),

]

interactive_ui/interactive_ui/urls.py
from django.contrib import admin
from django.urls import path, include
from interactive_ui import urls
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/', include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("interactive_player.urls")),
    path('moderator/', include("moderator_dashboard.urls")),
]

interactive_ui/moderator_dashboard/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views

app_name = "moderator_dashboard"

urlpatterns = [
    # ex: /moderator/
    path('', views.index, name='index'),
    # ex: /moderator/facelist
    path('facelist/', views.facelist, name="facelist"),    
    # ex: /moderator/facelist/10
    path('facelist/<int:face_id>/', views.facedetail, name='facedetail'),
    # ex: /moderator/facelist/10
    path('facelist/facedelete/<int:face_id>', views.facedelete, name='facedelete'),
    path('facelist/<int:face_id>/<str:sample_id>/<str:name>/<str:action>/<str:metadata>/', views.faceedit, name='faceedit'),
]

interactive_ui/accounts/models.py
from django.db import models

# Create your models here.

interactive_ui/interactive_player/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserFeedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.CharField(max_length=1024, default='', blank=True, null=True)
    time_window_id = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)   

interactive_ui/moderator_dashboard/models.py
from django.db import models

# Create your models here.
from datetime import datetime

from sqlalchemy import Table, Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import BYTEA
from sqlalchemy.ext.declarative import declared_attr, declarative_base
from sqlalchemy.orm import relationship

STATEMENT_TEXT_MAX_LENGTH = 255


class ModelBase(object):
    """
    An augmented base class for SqlAlchemy models.
    """

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True
    )

    created_at = Column(
        DateTime,
        default=datetime.now()
    )

    last_updated = Column(
        DateTime,
        default=datetime.now(),
        onupdate=datetime.now()
    )


Base = declarative_base(cls=ModelBase)


class SampleFaces(Base):
    """
    Sample face information model
    """
    __tablename__ = 'sample_faces'

    sample_id = Column(
        String(STATEMENT_TEXT_MAX_LENGTH),
        nullable=False
    )

    name = Column(
        String(STATEMENT_TEXT_MAX_LENGTH),
        nullable=False
    )

    meta_data = Column(
        Text(),
        nullable=True
    )

    action = Column(
        Text(),
        nullable=True
    )

    vectors = relationship('FeatureVectors', backref='face')
    imgdatas = relationship('FaceImages', backref='faceimg')


class FeatureVectors(Base):
    """
    Feature vectors of the registered sample faces
    """
    __tablename__ = 'feature_vectors'

    face_id = Column(
        Integer,
        ForeignKey('sample_faces.id', ondelete='CASCADE')
    )

    vector = Column(
        Text(),
        nullable=False
    )

class FaceImages(Base):

    #registered sample face images

    __tablename__ = 'face_images'

    face_id = Column(
        Integer,
        ForeignKey('sample_faces.id', ondelete='CASCADE')
    )

    imgdata = Column(
        BYTEA(),
        nullable=False
    )

interactive_ui/accounts/views.py
from django.shortcuts import render

# Create your views here.

interactive_ui/interactive_player/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from .models import UserFeedback
import time

# Create your views here.
def index(request):
    print(round(time.time()))
    return render(request, 'interactive_player/index.html',
                  {
                  })


def rtcdemo(request):
    return render(request, 'interactive_player/index_rtc.html',
                  {
                  })


def rtcmetatrack(request):
    return render(request, 'interactive_player/metatrack.html',
                  {
                  })


def downcount(request):
    remaining_time = 30 - int(time.time() % 30)
    window_id = int(time.time() / 30)
    return JsonResponse({'remaining':remaining_time, 'window_id': window_id}, status=200)


@login_required
def UserFeedbackView(request):
    feedback = request.POST['feedback']
    window_id = int(request.POST['window_id'])
    UserFeedback.objects.create(user=request.user, feedback=feedback, time_window_id=window_id)

    return HttpResponse('success', status=200)

interactive_ui/moderator_dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from interactive_player.models import UserFeedback
from django.db.models import Count
import time
from base64 import b64decode
from . import dbconnect
from django.http import HttpResponseRedirect
from django.urls import path, reverse

# Create your views here.
def check_admin(user):
    return user.is_superuser

@user_passes_test(check_admin)
def index(request):
    window_id = int(time.time() / 30)
    feedbacks = UserFeedback.objects.filter(time_window_id=window_id).values('feedback').annotate(fcount=Count('feedback')).order_by('fcount')[:10]
    return render(request, 'moderator_dashboard/dashboard.html',
                  {
                     'feedbacks': feedbacks
                  })
   
@user_passes_test(check_admin)
def feedback_sort(request):
    window_id = int(time.time() / 30)
    return render(request, 'moderator_dashboard/dashboard.html',
                  {
                  })
@user_passes_test(check_admin)
def facelist(request):
    window_id = int(time.time() / 30)
    facelist = dbconnect.get_facelist()
    return render(request, 'moderator_dashboard/facelist.html',
                  {
                     'facelist': facelist
                  })

@user_passes_test(check_admin)
def facedetail(request, face_id):
    window_id = int(time.time() / 30)
    face = dbconnect.get_facedetail(face_id)
    return render(request, 'moderator_dashboard/facedetail.html',
                  {
                     'face': face
                  })
@user_passes_test(check_admin)
def facedelete(request, face_id):
    window_id = int(time.time() / 30)
    dbconnect.delete_facedetail(face_id)
    return redirect(reverse('moderator_dashboard:facelist'))
    
@user_passes_test(check_admin)
def faceedit(request, face_id, sample_id, name, action, metadata):
    window_id = int(time.time() / 30)
    metadatadec = b64decode(metadata).decode('utf-8')
    dbconnect.update_facedetail(face_id, sample_id, name, action, metadatadec)
    return redirect(reverse('moderator_dashboard:facelist'))
    

interactive_ui/interactive_player/templates/interactive_player/index_demo.html
{% load static %}
<html>
    <head>
        <title>MistServer Meta-player</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=400">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        
        <link rel="shortcut icon" href={% static "imgs/play.svg" %}>
        <script>
          var maskmetadata = [];
        </script>

        <script src={% static "util.js" %}></script>
        <script src={% static "skins.js" %}></script>
        <script src={% static "controls.js" %}></script>
        <script src={% static "player.js" %}></script>

        <script src={% static "wrappers/html5.js" %}></script>
        <script src={% static "wrappers/videojs.js" %}></script>
        <script src={% static "wrappers/dashjs.js" %}></script>
        <script src={% static "wrappers/webrtc.js" %}></script>
        <script src={% static "wrappers/flash_strobe.js" %}></script>
        <script src={% static "wrappers/mews.js" %}></script>
        <script src={% static "wrappers/flv.js" %}></script>

        <script>
            try {
              //add these to point to the unminified and unconcatenated versions of the css files
              MistSkins.default.css.general = '{% static "skins/general.css" %}';
              MistSkins.dev.css.default = '{% static "skins/default.css" %}';
              
             
              //use local player scripts
              mistplayers.dashjs.scriptsrc = function(){ return '{% static "players/dash.all.min.js" %}'; };
              mistplayers.videojs.scriptsrc = function(){ return '{% static "players/video.js" %}'; };
              mistplayers.flv.scriptsrc = function(){ return '{% static "players/flv.min.js" %}'; };
              mistplayers.hlsjs.scriptsrc = function(){ return '{% static "players/hls.js" %}'; };
            }
            catch(e){}
        </script>
        <style>
            .mistvideo-progress .bar { background-color: transparent !important; } 
            body {
            padding: 0;
            margin: 0;
            width: 100vw;
            height: 100vh;
            background-color: #0f0f0f;
            color: #aaa;
            overflow: hidden;
            display: flex;
            flex-flow: column nowrap;
            align-items: center;
            }
            
            .videocontainer {
            flex-grow: 1;
            flex-shrink: 1;
            margin: 1em 0;
            display: flex;
            align-items: center;
            max-width: 100%;
            min-height: 4em;
            }
            
            .videocontainer * {
            /*outline: 1px solid red;*/
            }
            
            .streamopts {
            display: flex;
            flex-flow: row nowrap;
            z-index: 1;
            top: 0;
            flex-shrink: 0;
            width: 400px;
            flex-shrink: 0;
            min-height: 2em;
            }
            .streamopts > * {
            display: flex;
            flex-flow: column nowrap;
            width: 50%;
            }
            
            .controlcont {
            display: flex;
            flex-flow: row nowrap;
            align-items: baseline;
            }
            .controlcont > *:not(:first-child) {
            margin-left: 0.5em;
            }
            
            .streamOptions {
            flex-shrink: 1;
            width: 30em;
            min-height: 2em;
            }
            .streamOptions:focus {
            z-index: 99;
            }
            
            a {
            color: cyan;
            }
            
            
            h2 {
            margin: 0;
            }
            
            textarea {
            font-size: 0.8em;
            max-height: 20em;
            overflow-y: auto;
            }
    
            .box {
                    border: 3px solid #FF0000;
                    width: 0px;
                    height: 0px;
                    position: absolute;
                    opacity: 0.5;
                    cursor: move;
                }
    
            .textpanel {
            display: flex;
            flex-flow: row nowrap;
            top: 0;
            font-size: 2.0em;
            width: 1080px;
            flex-shrink: 0;
            min-height: 2em;
            }
            
        </style>
      
        <script>     
            var video;
            var MistVideoObject = {};
            var cont;
            var videlem;
            var textpanel;
            var opts = {
                stream: 'test',
                opts: {
                    host: location.protocol+"//"+location.hostname+":8080",
                    skin: "dev",
                    loop: true,
                    forcePlayer:"mews",
                }
            };
                        
            
            //some stream presets for the datalist
            var streams = [''];
            //some host presets for the datalist
            var hosts = ['http://localhost:8080'];
            try {
                var saved = JSON.parse(localStorage["embedtest_prev"]);
                if (saved.streams) { streams = saved.streams; }
                if (saved.hosts) { hosts = saved.hosts; }
            }
            catch (e) {}
    
            
            //init function that is called when the body is loaded
            function mistinit(forceStream) {
            console.warn("Testing page is initing a new player");
            if (MistVideoObject.reference) { MistVideoObject.reference.unload("Testing page is reloading player"); }
            if (forceStream) {
                opts.stream = forceStream;
                opts.opts.host = "http://localhost:8080";
            }
            
            document.body.innerHTML = ''; //reset the page
            document.body.appendChild(cont);           
            
            //and one for the actual stream
            var videocont = document.createElement('div');
            videocont.className = "videocontainer";
            document.body.appendChild(videocont);
            videlem = videocont;
    
            
            opts.opts.target = videocont;
            opts.opts.MistVideoObject = MistVideoObject;
            
    
            // added by nick
            var videotextpanel = document.createElement("textarea");
            videotextpanel.className = "textpanel";
    
            document.body.appendChild(videotextpanel);
            textpanel = videotextpanel;
            
            video = mistPlay(opts.stream,opts.opts);
            }
            
            
            function closestIndex(num, arr) {
            var curr = arr[0],
                diff = Math.abs(num - curr),
                index = 0;
    
            for (var val = 0; val < arr.length; val++) {
                let newdiff = Math.abs(num - arr[val]);
                
                // break if timediff is less than 100ms
                if (newdiff < 100) {
                    index = val;
                    break;  
                }
                if (newdiff < diff) {
                    diff = newdiff;
                    curr = arr[val];
                    index = val;
                }
            }
            return index;
            }
    
    
            function removeElementsByClass(className) {
            var elements = document.getElementsByClassName(className);
            while (elements.length > 0) {
                elements[0].parentNode.removeChild(elements[0]);
            }
            }
    
    
            setInterval(drawmetaimage, 33);
    
            var metapanelInit = 0;
            let image = null;
            var ctx = null;
            var layer1 = null;
            var last_timestamp = null;
    
            function drawmetaimage() {
            videlement = document.getElementsByTagName("video");
    
            if(typeof(videlement[0]) !== 'undefined') {
                if (!metapanelInit) {
    
                }
                
                videlement[0].onplay = function() {
                maskmetadata = [];
                //nick added
                
                let layer1canvas = document.createElement('canvas');
                layer1canvas.id = "layer1";
                layer1canvas.width = videlement[0].getBoundingClientRect().width;
                layer1canvas.height = videlement[0].getBoundingClientRect().height;
                layer1canvas.style.position = "absolute";
                layer1canvas.style.top = "0px";
                layer1canvas.style.left = "0px";
                layer1canvas.style.zIndex = 2;
                layer1canvas.style.opacity = "0.3";
    
                videlement[0].parentNode.appendChild(layer1canvas);
                };
    
                if (layer1 == null)
                layer1 = document.getElementById('layer1');
                
    
                if (layer1 == null)
                return;
    
                if (ctx == null) {
                ctx=layer1.getContext('2d');
                ctx.strokeStyle = "red";
                ctx.fillStyle = "red";
                ctx.lineWidth = 5;
                }
                if (maskmetadata.length > 0) {
                let cur_time = videlement[0].currentTime * 1000;
                if ((cur_time - last_timestamp) > 150)
                    ctx.clearRect(0, 0, layer1.width, layer1.height);
                maskdata = maskmetadata[closestIndex(videlement[0].currentTime * 1000, maskmetadata)];
                if (Math.abs(cur_time - maskdata.timestamp) > 1500) {
                console.warn("out of sync, ignoring meta");
                return;
                }
                let arrayLen = maskdata.metadata.length;
                for (let i = 0; i < arrayLen; i++) {
                    let bbox = maskdata.metadata[i]["bbox"];
                    let bboxarray = bbox.split(",");
                    let metalink = maskdata.metadata[i]["metadata"];
    
                    if (i == 0) {
                    // removeElementsByClass("box");
                    let new_element = layer1.cloneNode(true);
                    layer1.parentNode.replaceChild(new_element, layer1);
                    layer1 = new_element;
                    ctx=layer1.getContext('2d');
                    ctx.strokeStyle = "red";
                    ctx.fillStyle = "red";
                    ctx.lineWidth = 5;
                    
                    ctx.clearRect(0, 0, layer1.width, layer1.height);
                    last_timestamp = maskdata.timestamp;
                    }
    
                    let path = new Path2D();
                    path.rect(bboxarray[0] * layer1.width/400, bboxarray[1] * layer1.height/300, bboxarray[2] * layer1.width/400, bboxarray[3] * layer1.height/300);
                    ctx.strokeStyle = "red";
                    ctx.fillStyle = "red";
                    ctx.lineWidth = 5;
                    ctx.stroke(path); 
    
                    layer1.addEventListener('click', function(event) {
                    event.preventDefault();
                    event.stopPropagation();
                    if (ctx.isPointInPath(path, event.offsetX, event.offsetY)) {
                        console.log(metalink);
                        window.open(metalink, "_blank");
                    }
    
                    });  
                }
                return;
                }
            }
            }
    
            function go() {
                cont = document.createElement("div");           
                mistinit();
            }
            
        </script>
    </head>

    <body onload=go()>
    </body>
</html>

interactive_ui/moderator_dashboard/templates/_content_header.html
<header class="top-head container-fluid">

    <!-- Right navbar -->
    <ul class="list-inline navbar-right top-menu top-right-menu">
        <!-- Notification -->

        <!-- /Notification -->

        <!-- user login dropdown start-->
        <li class="dropdown text-center">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="username">{{ user.name|default:"USER" }}</span> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu extended pro-menu fadeInUp animated" tabindex="5003" style="overflow: hidden; outline: none;">
                <li><a href=""><i class="fa fa-briefcase"></i>Profile</a></li>
                <li><a href=""><i class="fa fa-sign-out"></i> Log Out</a></li>
            </ul>
        </li>
        <!-- user login dropdown end -->
    </ul>
    <!-- End right navbar -->

</header>

interactive_ui/moderator_dashboard/templates/_left_panel.html
{% load static %}
<aside class="left-panel">
    <!-- brand -->
    <div class="logo">
        <a href="" class="logo-expanded">
            <img src="{% static "imgs/logo.svg" %}"  style="height:30px" alt="logo">
            <span class="nav-label"></span>
        </a>
    </div>
    <!-- / brand -->
    <!-- Navbar Start -->
    <nav class="navigation">
        <ul class="list-unstyled">
            <li class="has-submenu"><a href="#"><i class="ion-home"></i> <span class="nav-label">Dashboard</span></a>
                <ul class="list-unstyled">
                    <li><a href="">Overview</a></li>
                </ul>
            </li>
            <li class="has-submenu"><a href="#"><i class="fa fa-money"></i> <span class="nav-label">Analytics</span></a>
                <ul class="list-unstyled">
                    <li><a href="">Analytics</a></li>
                </ul>
            </li>
            <li class="has-submenu"><a href="#"><i class="fa fa-money"></i> <span class="nav-label">Face List</span></a>
                <ul class="list-unstyled">
                    <li><a href="{% url 'moderator_dashboard:facelist' %}">Face List</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</aside>

interactive_ui/moderator_dashboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>interactive player feedback</title>

    <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
    <link href={% static "css/bootstrap-reset.css" %} rel="stylesheet">


    <!--Animation css-->
    <link href={% static "css/animate.css" %} rel="stylesheet">

    <!--Icon-fonts css-->
    <link href={% static "assets/font-awesome/css/font-awesome.css" %} rel="stylesheet" />
    <link href={% static "assets/ionicon/css/ionicons.min.css" %} rel="stylesheet" />

    <!-- sweet alerts -->
    <link href={% static "assets/sweet-alert/sweet-alert.min.css" %} rel="stylesheet">

    <link href={% static "assets/select2/select2.css" %} rel="stylesheet"/>

    <!-- Custom styles for this template -->
    <link href={% static "css/style.css" %} rel="stylesheet">
    <link href={% static "css/helper.css" %} rel="stylesheet">
    <link href={% static "css/style-responsive.css" %} rel="stylesheet" />

    {% block header_stuff %}
    {% endblock header_stuff %}
</head>
<body>

    {% include '_left_panel.html' %}
    <section class="content">
    {% include '_content_header.html' %}
    {% block content %}
    {% endblock %}
    </section>



    <!-- js placed at the end of the document so the pages load faster -->
    <script src={% static "js/jquery.js" %}></script>
    <script src={% static "js/bootstrap.min.js" %}></script>
    <script src={% static "js/modernizr.min.js" %}></script>
    <script src={% static "js/pace.min.js" %}></script>
    <script src={% static "js/wow.min.js" %}></script>
    <script src={% static "js/jquery.scrollTo.min.js" %}></script>
    <script src={% static "js/jquery.nicescroll.js" %} type="text/javascript"></script>
    <script src={% static "assets/chat/moment-2.2.1.js" %}></script>

    <!-- sweet alerts -->
    <script src={% static "assets/sweet-alert/sweet-alert.min.js" %}></script>
    <script src={% static "assets/sweet-alert/sweet-alert.init.js" %}></script>
    <script src={% static "assets/select2/select2.min.js" %} type="text/javascript"></script>

    <script src={% static "js/jquery.app.js" %}></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>

<script type="text/javascript">

</script>

{% block javascripts %}
{% endblock javascripts %}

</body>
</html>

interactive_ui/moderator_dashboard/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block header_stuff %}
    <link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css" rel="stylesheet"/>
    <link href={% static "css/toggle_button.css" %} rel="stylesheet" />
{% endblock %}


{% block content %}
<div class="wraper container-fluid" id="overview_main">
    <div class="page-title">
        <h3 class="title">Top 10 feedbacks by users</h3>
    </div>

    <div class="row">
        <div class="col-md-12 col-sm12 col-xs-12 m-t-30" id="table_contents">
            <table id="datatable" class="table table striped table-bordered">
                <thead>
                <tr>
                    <th>Feedback</th>
                    <th>Number of Votes</th>
                    <th>Time Window</th>
                </tr>
                </thead>
                <tbody>
                    {% for feedback in feedbacks %}
                    <tr>
                        <td>{{ feedback.feedback }}</td>
                        <td>{{ feedback.fcount }}</td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>

<script>
    function dt_init() {
        table_obj = $('#datatable').DataTable({

        });
    }
    $(document).ready(function () {
        dt_init();
    });
</script>
{% endblock %}

interactive_ui/moderator_dashboard/templates/moderator_dashboard/facedetail.html
{% extends "base.html" %}
{% load static %}

{% block header_stuff %}
    <link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css" rel="stylesheet"/>
    <link href={% static "css/toggle_button.css" %} rel="stylesheet" />
{% endblock %}


{% block content %}
<div class="wraper container-fluid" id="overview_main">
    <div class="page-title">
        <h3 class="title">registered face edit</h3>
    </div>
    <script>
        href="{% url 'moderator_dashboard:facelist' %}" + "{{ face.id }}"
        function saveitem() {
            let sample_id = document.getElementById('sample_id').value;
            let facename = document.getElementById('facename').value;
            let metadata = btoa(document.getElementById('metadata').value);
            let action = document.getElementById('action').value;
            console.log(sample_id, facename, action, metadata);

            href = href + "/" + sample_id + "/" + facename + "/" + action + "/" + metadata
            window.location.replace(href);
        }
    </script>
    <div class="row">
        <div class="col-md-12 col-sm12 col-xs-12 m-t-30" id="table_contents">
            <table id="datatable" class="table table striped table-bordered">
                <thead>
                <tr>
                    <th>sample_id</th>
                    <th>name</th>
                    <th>metadata</th>
                    <th>action</th>
                    <th>imgdata</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="text" id="sample_id" name="sample_id" value={{ face.sample_id }}></td>
                        <td><input type="text" id="facename" name="facename" value={{ face.name }}></td>
                        <td><input type="text" id="metadata" name="metadata" value={{ face.metadata }}></td>                        
                        <td><input type="text" id="action" name="action" value={{ face.action }}></td>
                        <td><img src="data:image;base64,{{ face.imgdata }}"></td>
                        <td><button type="button" onclick="saveitem()">save</button></td>
                        <td><a href="{% url 'moderator_dashboard:facedelete' face.id %}"><button type="button">delete</button></a></td>
                    </tr>                    
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>

<script>
    function dt_init() {
        table_obj = $('#datatable').DataTable({

        });
    }
    $(document).ready(function () {
        dt_init();
    });
</script>
{% endblock %}